# .github/workflows/build.yml
name: build

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: make setup
      - run: make check
      - run: bash <(curl -s https://codecov.io/bash)

  test-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: make setup
      - run: make test-package
